[build]
builder = "dockerfile"

[[services]]
name = "backend"
dockerfile = "backend/Dockerfile"
directory = "backend"

[[services]]
name = "frontend"
dockerfile = "frontend/Dockerfile"
directory = "frontend"